apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user
          image: user-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080  # user service runs on 8080 inside the container
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8080  # Exposes externally on 8082
      targetPort: 8080  # Maps to container's 8080
  type: LoadBalancer
